# These are supported funding model platforms

github: [vedic-lang,ptprashanttripathi]
patreon: ptprashanttripathi
open_collective: ptprashanttripathi
ko_fi: ptprashanttripathi
custom: ["https://www.paypal.me/ptprashanttripathi"]
