# This is a basic workflow to help you get started with Actions
name: RUST_WASM_BOT

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: "Build Wasm pack"
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@master
          with:
            fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

        - name: Install Rust
          uses: actions-rs/toolchain@v1
          with:
              profile: default
              toolchain: stable
              target: x86_64-unknown-linux-gnu

        - name: Build WASM
          shell: bash
          run: |
            git clone https://github.com/vedic-lang/vedic.git
            cd vedic
            curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
            wasm-pack build wasm --target no-modules
            cd ..
            cp ./vedic/wasm/pkg/* ./wasm
            rm -rf ./vedic

        - name: Upload WASM to Github
          run: |
            git config user.name PtPrashantTripathi
            git config user.email ptprashanttripathi@outlook.com
            git add .
            git commit -m "[PanditBot] Updating Repos Data $(date +%Y-%m-%d_%H-%M-%S)"
            git push --quiet